[package]
name = "ruuvitag"
version = "0.1.0"
authors = ["Mikko ViitamÃ¤ki <mikko.viitamaki+github@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

